### ISSUE TITLE
Unable to install packages from readme instructions (Ubuntu 20.04)

### ISSUE THREAD

**Issue by Vladislav-Lukyanuk** [himozzza/essx8336#2]
```
vladislav:~$ sudo apt-get install firmware-linux firmware-alsa-sof
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package firmware-linux is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'firmware-linux' has no installation candidate
E: Unable to locate package firmware-alsa-sof

```

**Comment by Vladislav-Lukyanuk** [comment]
I converted rpm packages to deb and install them, but it doesn't help to me. Only dummy output showen.

**Comment by himozzza** [comment]
Приветствую.
На 8м поколении процессоров это успешно работает. В том числе и в Ubuntu.
Пакетов  firmware-alsa-sof там нет, они были распакованы вручную, без
преобразования. Вся работа завязана в основном на них, мало включить
поддержку в ядре.
Alt Linux недавно добавил поддержку данного кодека по запросу, ядро
5.10.0-73-un-def, пакеты firmware-alsa-sof имеются у них в репозитории, так
же работало на восьмом поколении.

Если у вас фиктивный выход с этим ядром, значит вам нужны именно
firmware-alsa-sof. И после их установки, не факт что звук всё-таки
заработает с вашей архитектурой.


чт, 18 нояб. 2021 г. в 10:17, Vladislav-Lukyanuk ***@***.***>:

**Comment by Vladislav-Lukyanuk** [comment]
Thanks for you reply.
Can you write more detailed instruction for Ubuntu?

**Comment by himozzza** [comment]
К сожалению нет. Просто распаковка пакетов в директории и сделать
update-initramfs.

чт, 18 нояб. 2021 г., 10:45 Vladislav-Lukyanuk ***@***.***>:

**Comment by Vladislav-Lukyanuk** [comment]
В какие-то конкретные директории? или просто распаковать локально и в этой папке выполнить ?

**Comment by himozzza** [comment]
Внутри rpm лежат катологи, их нужно распаковать в корень /

чт, 18 нояб. 2021 г., 10:55 Vladislav-Lukyanuk ***@***.***>:

**Comment by Vladislav-Lukyanuk** [comment]
Спасибо =)
